### ISSUE TITLE
No results for about 0.1% of the players

### ISSUE THREAD

**Issue by Black-Hole** [Mojang/AccountsClient#3] opened 2014-01-15 22:52 UTC
AccountsClient returns no result for several players. About 50 of 36000.

Some example user names:
Pups1924
derJonas1304
TheFlo2001
flash3838
Plarun
zxZDerShaenZxz
koffermodus
LPXerios
TheCheater1998
ReyTronix
CrafterRamon2000
FCAugsburgs

**Comment by jomo** [comment] 2014-01-15 22:59
Those are not paid accounts.
https://minecraft.net/haspaid.jsp?user=[username]

**Comment by Black-Hole** [comment] 2014-01-15 23:09
That explains the result.
At the time they visited my server, they had a paid account. Maybe paid by a gift code from ebay.

**Comment by jomo** [comment] 2014-01-15 23:20
That would be a bit strange. Maybe these users cancelled their accounts?
Maybe they used one of the bugs that allowed users to log in as anyone with a bit of hacking.

**Comment by Black-Hole** [comment] 2014-01-15 23:40
I don't think that they closed their accounts. The bug with changing user name while authorizing was fixed with a day. The login dates of the players span from 2011 until the intruduction of 1.7.2 on my server.

A better explanation:
None of the payment methods offered by Mojang in Germany are suitable for pupils. They don't have bank accounts. So they search for alternative methods to pay with something like a PaySafe card. They even pay more than the usual 20 €.
Often these gift codes where paid with stolen credit card numbers or from reduced bulk accounts for education. Many of these gift code dealers offers new codes if the old ones are blocked by Mojang.

**Comment by Dinnerbone** [comment] 2014-04-07 08:10
Closing as these are not valid (paid) accounts and this is thus working as intended.

**Closed as completed by Dinnerbone** 2014-04-07 08:10 UTC
